version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:00'
      timezone: 'America/New_York'
    reviewers:
      - 'sbolel'
    labels:
      - 'dependencies'
    rebase-strategy: 'auto'
    versioning-strategy: increase
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
