# This GitHub Actions workflow automatically merges pull requests created by Dependabot
# for patch and minor version upgrades. It triggers on pull request events, checks if
# the actor is Dependabot, and then uses the dependabot/fetch-metadata action to get
# metadata about the dependency update. If the update is a semver patch or semver
# minor upgrade, it enables auto-merge for the Dependabot PR using the GitHub CLI.
name: Dependabot auto-merge

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enable auto-merge for Dependabot PRs
        # In the 'if' block below, the version-update:* values should always
        # match the Dependabot update strategy in `.github/dependabot.yml`.
        # Dependabot should be configured to ignore semver-major updates, and
        # this workflow should only merge semver-patch and semver-minor updates,
        # adding a second layer of protection against breaking changes.
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
